config/routes.rb
Rails.application.routes.draw do
  resources :conciertos
 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concierto.rb
class Concierto < ApplicationRecord
  belongs_to :grupo
end

app/models/grupo.rb
class Grupo < ApplicationRecord
  has_many :concierto
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/conciertos_controller.rb
class ConciertosController < ApplicationController
  def index
    @conciertos = Concierto.all
  end
  def new
    @concierto = Concierto.new
    @grupos = Grupo.all
  end

  def show
    @concierto = Concierto.find(params[:id])
  end

  def edit

  end

  def create
    @concierto = Concierto.new(concierto_params) #Strong parameters, previene ataques de mass assignment
      respond_to do |format| if @concierto.save
          format.html { redirect_to @concierto, notice: 'El concierto fue creado correctamente.'}
        else
          format.html { render :new }
        end
      end
  end

    private
    def concierto_params
      params.require(:concierto).permit(:lugar, :personas_en_concierto, :conciertos_en_el_mes, :fecha_ultimo_concierto, :duracion)
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/conciertos_helper.rb
module ConciertosHelper
end

app/views/conciertos/_form.html.erb
<%= form_with(model: [@grupo, concierto], local: true) do |form| %>
<% if concierto.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(concierto.errors.count, "error") %> prohibited this concierto from being saved:</h2>
    <ul>
      <% concierto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="field">
  <%= form.label :lugar %>
  <%= form.text_field :lugar %>
  <br>
  <%= form.label :personas_en_concierto %>
  <%= form.text_field :personas_en_concierto %>
  <br>
  <%= form.label :conciertos_en_el_mes %>
  <%= form.text_field :conciertos_en_el_mes %>
  <br>
  <%= form.label :fecha_ultimo_concierto %>
  <%= form.text_field :fecha_ultimo_concierto %>
  <br>
  <%= form.label :duracion %>
  <%= form.text_field :duracion %>
  <br>
</div>

<div class="field">
  <%= form.label :grupo %>
  <%= form.select :grupo_id, @grupo.map{|grupo| [grupo.nombre, grupo.id] }, prompt: "Seleccione un grupo.." %>
</div>

<div class="actions">
  <%= form.submit %>
</div>
<% end %>

app/views/conciertos/edit.html.erb
<h1>Editar Concierto</h1>














<%= link_to 'Back', conciertos_path %>

app/views/conciertos/index.html.erb
<h1>Conciertos</h1>
<table>
  <thead>
    <tr>
      <th>lugar</th>
      <th>Asistentes</th>
      <th>Conciertos en el mes</th>
      <th>Último concierto</th>
      <th>Duración</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @conciertos.each do |concierto| %>
      <tr>
        <td><%= concierto.lugar %></td>
        <td><%= concierto.personas_en_concierto %></td>
        <td><%= concierto.conciertos_en_el_mes %></td>
        <td><%= concierto.fecha_ultimo_concierto %></td>
        <td><%= concierto.duracion %></td>
        <td><%=link_to 'Mostrar', concierto%></td>
        <td> <%= link_to 'Editar', edit_concierto_path(concierto) %></td>
        <td> <%= link_to 'Eliminar concierto', concierto, method: :delete, data: {confirm: 'Estas seguro ?'} %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'Nuevo Concierto', new_concierto_path %>

app/views/conciertos/new.html.erb
<h1>Crear nuevo Concierto</h1>


<%= render 'form', concierto: @concierto %>

<%= link_to 'Back', conciertos_path %>

app/views/conciertos/show.html.erb
 
<h1>Mostrar Conciertos</h1>


<p>
  <strong>Grupo:</strong>
  <%= @concierto.grupo %>
</p>
<p>
  <strong>Lugar:</strong>
  <%= @concierto.lugar %>
</p>

<p>
  <strong>Asistentes:</strong>
  <%= @concierto.personas_en_concierto %>
</p>

<p>
  <strong>Fecha:</strong>
  <%= @concierto.fecha_ultimo_concierto %>
</p>

<p>
  <strong>Duración:</strong>
  <%= @concierto.duracion %>
</p>

<%= link_to 'Back', conciertos_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DesafioProductoraDeEventos</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>